management:
  server:
    port: 0
server:
  ssl:
    enabled: false
  servlet:
    session:
      cookie:
        secure: false
logging:
  structured:
    ecs:
      service:
        environment: test
