package com.example.commons.accounts.review;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;

import com.example.commons.accounts.report.ReportDocument;
import com.example.commons.accounts.report.ReportDocument.Tile;
import com.example.commons.accounts.review.ReviewDtos.PopulationEntryResponse;
import com.example.commons.accounts.review.ReviewReportModel.ItemSection;
import com.example.commons.accounts.review.ReviewReportModel.PopulationSection;

/**
 * Lays an account review report out as PDF with OpenPDF, as xlsx with Apache POI's
 * streaming workbook, and as csv.
 */
public class DefaultReviewReportRenderer implements ReviewReportRenderer {

	private static final Color GREEN = new Color(0x15803d);

	private static final Color BLUE = new Color(0x1d4ed8);

	private static final Color RED = new Color(0xb91c1c);

	private static final Color AMBER = new Color(0xb45309);

	private static final Color INK = new Color(0x1f2937);

	private static final List<String> ACTIVE_HEADERS = List.of("No.", "Name", "Username", "Department", "Created",
			"Last Login", "Roles", "Review Outcome", "Remarks", "Review Date");

	private static final List<String> SUSPENDED_HEADERS = List.of("No.", "Name", "Username", "Department", "Created",
			"Last Login", "Roles", "Suspended", "Suspended By", "Reason", "Review Outcome", "Remarks", "Review Date");

	private static final List<String> REMOVED_HEADERS = List.of("Username", "Name", "Department", "Created",
			"Last Login", "Removed", "Removed By", "Reason", "Note");

	private static final float[] ACTIVE_WIDTHS = { 0.6f, 1.8f, 1.5f, 1.4f, 1.5f, 1.5f, 2.2f, 1.6f, 2.2f, 1.5f };

	private static final float[] SUSPENDED_WIDTHS = { 0.5f, 1.5f, 1.3f, 1.2f, 1.3f, 1.3f, 1.8f, 1.3f, 1.1f, 1.1f, 1.4f,
			1.8f, 1.3f };

	private static final float[] REMOVED_WIDTHS = { 1.5f, 1.6f, 1.3f, 1.3f, 1.4f, 1.4f, 1.1f, 1.2f, 1.8f };

	private static final List<String> CSV_HEADERS = List.of("Category", "No.", "Name", "Username", "Department",
			"Created", "Last Login", "Roles", "Suspended / Removed On", "Suspended / Removed By", "Reason",
			"Review Outcome", "Remarks", "Review Date", "Confirmed By", "Confirmed On");

	@Override
	public byte[] pdf(ReviewReportModel model) {
		DateTimeFormatter dateTime = dateTime(model.zone());
		ReportDocument document = new ReportDocument(title(model) + " Report",
				title(model) + " " + format(model.periodStart(), model.periodEnd()), model.draft());
		document.keyValues(List.of(new String[] { "Review", title(model) },
				new String[] { "Review Period", format(model.periodStart(), model.periodEnd()) },
				new String[] { "Due Date", day(model.dueDate()) },
				new String[] { "Completed",
						model.completedAt() == null ? null
								: dateTime.format(model.completedAt()) + " by " + model.completedBy() },
				new String[] { "Generated On", dateTime.format(model.generatedAt()) },
				new String[] { "Generated By", model.generatedBy() }));
		itemsPdf(document, "Active", model.active(), ACTIVE_HEADERS, ACTIVE_WIDTHS, dateTime, false);
		itemsPdf(document, "Suspended", model.suspended(), SUSPENDED_HEADERS, SUSPENDED_WIDTHS, dateTime, true);
		PopulationSection removed = model.removed();
		document.heading("Removed Accounts");
		document.text(removed.confirmed()
				? "Confirmed by " + removed.confirmedBy() + " on " + dateTime.format(removed.confirmedAt()) + ". "
						+ removed.entries().size() + " accounts." + (removed.note() == null ? "" : " " + removed.note())
				: "Not yet confirmed.");
		document.table(REMOVED_HEADERS, REMOVED_WIDTHS, removedCells(removed.entries(), dateTime));
		return document.toBytes();
	}

	/**
	 * Lays out the summary, the breakdown by department and the detailed results of one
	 * category of accounts.
	 */
	private static void itemsPdf(ReportDocument document, String category, ItemSection section, List<String> headers,
			float[] widths, DateTimeFormatter dateTime, boolean suspended) {
		ReviewReportModel.Summary summary = section.summary();
		document.heading(category + " Accounts Review Summary");
		List<Tile> tiles = new ArrayList<>(
				List.of(new Tile(String.valueOf(summary.confirmed()), "Confirmed (no role changes)", GREEN),
						new Tile(String.valueOf(summary.confirmedRolesEdited()), "Confirmed (roles edited)", BLUE),
						new Tile(String.valueOf(summary.removed()), "Removed", RED)));
		if (summary.pending() > 0) {
			tiles.add(new Tile(String.valueOf(summary.pending()), "Pending", AMBER));
		}
		tiles.add(new Tile(String.valueOf(summary.total()), "Total accounts", INK));
		document.tiles(tiles);
		document.heading(category + " Accounts: Breakdown by Department");
		List<String[]> departments = new ArrayList<>();
		for (ReviewReportModel.DepartmentRow row : section.departments()) {
			departments.add(new String[] { row.department(), String.valueOf(row.confirmed()),
					String.valueOf(row.confirmedRolesEdited()), String.valueOf(row.removed()),
					String.valueOf(row.pending()), String.valueOf(row.total()) });
		}
		document.table(List.of("Department", "Confirmed", "Confirmed (Roles Edited)", "Removed", "Pending", "Total"),
				new float[] { 3, 1, 1.4f, 1, 1, 1 }, departments);
		document.heading(category + " Accounts: Detailed Results");
		document.table(headers, widths, itemCells(section.items(), dateTime, suspended));
	}

	private static List<String[]> itemCells(List<ReviewReportModel.ItemRow> rows, DateTimeFormatter dateTime,
			boolean suspended) {
		List<String[]> cells = new ArrayList<>();
		for (ReviewReportModel.ItemRow row : rows) {
			cells.add(itemCells(row, dateTime, suspended));
		}
		return cells;
	}

	private static List<String[]> removedCells(List<PopulationEntryResponse> entries, DateTimeFormatter dateTime) {
		List<String[]> rows = new ArrayList<>();
		for (PopulationEntryResponse entry : entries) {
			rows.add(new String[] { entry.username(), entry.name(), entry.department(),
					time(entry.createdAt(), dateTime), time(entry.lastLoginAt(), dateTime),
					time(entry.occurredAt(), dateTime), entry.actor(), entry.reasonCode(), entry.reasonNote() });
		}
		return rows;
	}

	@Override
	public byte[] xlsx(ReviewReportModel model) {
		DateTimeFormatter dateTime = dateTime(model.zone());
		SXSSFWorkbook workbook = new SXSSFWorkbook(100);
		try {
			CellStyle bold = workbook.createCellStyle();
			Font font = workbook.createFont();
			font.setBold(true);
			bold.setFont(font);
			Sheet summary = workbook.createSheet("Summary");
			int row = 0;
			if (model.draft()) {
				row = writeRow(summary, row, bold, "DRAFT: generated from an open review, not audit evidence");
			}
			row = writeRow(summary, row, null, "Review", title(model));
			row = writeRow(summary, row, null, "Review Period", format(model.periodStart(), model.periodEnd()));
			row = writeRow(summary, row, null, "Due Date", day(model.dueDate()));
			row = writeRow(summary, row, null, "Completed", model.completedAt() == null ? ""
					: dateTime.format(model.completedAt()) + " by " + model.completedBy());
			row = writeRow(summary, row, null, "Generated On", dateTime.format(model.generatedAt()));
			row = writeRow(summary, row, null, "Generated By", model.generatedBy());
			row = summaryBlock(summary, row, "Active accounts", model.active(), bold);
			summaryBlock(summary, row, "Suspended accounts", model.suspended(), bold);
			itemSheet(workbook, "Active accounts", model.active(), ACTIVE_HEADERS, dateTime, false, bold);
			itemSheet(workbook, "Suspended accounts", model.suspended(), SUSPENDED_HEADERS, dateTime, true, bold);
			removedSheet(workbook, model.removed(), dateTime, bold);
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			workbook.write(out);
			return out.toByteArray();
		}
		catch (IOException ex) {
			throw new UncheckedIOException(ex);
		}
		finally {
			workbook.dispose();
		}
	}

	/**
	 * Writes the outcomes and the breakdown by department of one category of accounts and
	 * returns the next free row.
	 */
	private static int summaryBlock(Sheet sheet, int start, String label, ItemSection section, CellStyle bold) {
		ReviewReportModel.Summary summary = section.summary();
		int row = start + 1;
		row = writeRow(sheet, row, bold, label, "Accounts");
		row = writeRow(sheet, row, null, "Confirmed", String.valueOf(summary.confirmed()));
		row = writeRow(sheet, row, null, "Confirmed (Roles Edited)", String.valueOf(summary.confirmedRolesEdited()));
		row = writeRow(sheet, row, null, "Removed", String.valueOf(summary.removed()));
		row = writeRow(sheet, row, null, "Pending", String.valueOf(summary.pending()));
		row = writeRow(sheet, row, null, "Total", String.valueOf(summary.total()));
		row++;
		row = writeRow(sheet, row, bold, "Department", "Confirmed", "Confirmed (Roles Edited)", "Removed", "Pending",
				"Total");
		for (ReviewReportModel.DepartmentRow department : section.departments()) {
			row = writeRow(sheet, row, null, department.department(), String.valueOf(department.confirmed()),
					String.valueOf(department.confirmedRolesEdited()), String.valueOf(department.removed()),
					String.valueOf(department.pending()), String.valueOf(department.total()));
		}
		return row;
	}

	private static void itemSheet(SXSSFWorkbook workbook, String name, ItemSection section, List<String> headers,
			DateTimeFormatter dateTime, boolean suspended, CellStyle bold) {
		Sheet sheet = workbook.createSheet(name);
		int row = writeRow(sheet, 0, bold, headers.toArray(String[]::new));
		for (String[] cells : itemCells(section.items(), dateTime, suspended)) {
			row = writeRow(sheet, row, null, cells);
		}
	}

	private static void removedSheet(SXSSFWorkbook workbook, PopulationSection section, DateTimeFormatter dateTime,
			CellStyle bold) {
		Sheet sheet = workbook.createSheet("Removed accounts");
		int row = writeRow(sheet, 0, null, "Confirmed", section.confirmed() ? "Yes" : "No");
		if (section.confirmed()) {
			row = writeRow(sheet, row, null, "Confirmed By", section.confirmedBy());
			row = writeRow(sheet, row, null, "Confirmed On", dateTime.format(section.confirmedAt()));
			row = writeRow(sheet, row, null, "Note", section.note() == null ? "" : section.note());
		}
		row++;
		row = writeRow(sheet, row, bold, REMOVED_HEADERS.toArray(String[]::new));
		for (String[] cells : removedCells(section.entries(), dateTime)) {
			row = writeRow(sheet, row, null, cells);
		}
	}

	private static int writeRow(Sheet sheet, int index, CellStyle style, String... values) {
		Row row = sheet.createRow(index);
		for (int column = 0; column < values.length; column++) {
			org.apache.poi.ss.usermodel.Cell cell = row.createCell(column);
			cell.setCellValue(values[column] == null ? "" : values[column]);
			if (style != null) {
				cell.setCellStyle(style);
			}
		}
		return index + 1;
	}

	@Override
	public byte[] csv(ReviewReportModel model) {
		DateTimeFormatter dateTime = dateTime(model.zone());
		StringBuilder csv = new StringBuilder("﻿");
		csv.append(csvLine(CSV_HEADERS.toArray(String[]::new)));
		for (ReviewReportModel.ItemRow item : model.active().items()) {
			csv.append(csvLine(csvCells("Active", item, dateTime)));
		}
		for (ReviewReportModel.ItemRow item : model.suspended().items()) {
			csv.append(csvLine(csvCells("Suspended", item, dateTime)));
		}
		PopulationSection removed = model.removed();
		int number = 0;
		for (PopulationEntryResponse entry : removed.entries()) {
			csv.append(csvLine("Removed", String.valueOf(++number), entry.name(), entry.username(), entry.department(),
					time(entry.createdAt(), dateTime), time(entry.lastLoginAt(), dateTime), null,
					time(entry.occurredAt(), dateTime), entry.actor(), entry.reasonCode(), null, entry.reasonNote(),
					null, removed.confirmedBy(), time(removed.confirmedAt(), dateTime)));
		}
		return csv.toString().getBytes(StandardCharsets.UTF_8);
	}

	private static String[] csvCells(String category, ReviewReportModel.ItemRow row, DateTimeFormatter dateTime) {
		return new String[] { category, String.valueOf(row.number()), row.name(), row.username(), row.department(),
				time(row.createdAt(), dateTime), time(row.lastLoginAt(), dateTime), row.roles(),
				time(row.suspendedAt(), dateTime), row.suspendedBy(), row.suspensionReason(), row.outcome(),
				row.remark(), time(row.decidedAt(), dateTime), null, null };
	}

	/**
	 * Returns one csv line. A value that a spreadsheet would read as a formula is
	 * prefixed with an apostrophe, so a name cannot run one when the file is opened.
	 */
	private static String csvLine(String... values) {
		List<String> cells = new ArrayList<>();
		for (String value : values) {
			String text = value == null ? "" : value;
			if (!text.isEmpty() && "=+-@\t\r".indexOf(text.charAt(0)) >= 0) {
				text = "'" + text;
			}
			cells.add("\"" + text.replace("\"", "\"\"") + "\"");
		}
		return String.join(",", cells) + "\r\n";
	}

	private static String title(ReviewReportModel model) {
		return model.privileged() ? "Privileged Account Review" : "Non-privileged Account Review";
	}

	private static String[] itemCells(ReviewReportModel.ItemRow row, DateTimeFormatter dateTime, boolean suspended) {
		List<String> cells = new ArrayList<>(List.of(String.valueOf(row.number()), nonNull(row.name()),
				nonNull(row.username()), nonNull(row.department()), nonNull(time(row.createdAt(), dateTime)),
				nonNull(time(row.lastLoginAt(), dateTime)), nonNull(row.roles())));
		if (suspended) {
			cells.add(nonNull(time(row.suspendedAt(), dateTime)));
			cells.add(nonNull(row.suspendedBy()));
			cells.add(nonNull(row.suspensionReason()));
		}
		cells.add(nonNull(row.outcome()));
		cells.add(nonNull(row.remark()));
		cells.add(nonNull(time(row.decidedAt(), dateTime)));
		return cells.toArray(String[]::new);
	}

	private static String nonNull(String value) {
		return value == null ? "" : value;
	}

	private static String time(Instant instant, DateTimeFormatter dateTime) {
		return instant == null ? null : dateTime.format(instant);
	}

	private static String format(LocalDate start, LocalDate end) {
		return day(start) + " - " + day(end);
	}

	private static String day(LocalDate date) {
		return DateTimeFormatter.ofPattern("d MMM yyyy", Locale.ENGLISH).format(date);
	}

	private static DateTimeFormatter dateTime(ZoneId zone) {
		return DateTimeFormatter.ofPattern("d MMM yyyy HH:mm", Locale.ENGLISH).withZone(zone);
	}

}
