package com.example.commons.accounts.review;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;

import com.example.commons.accounts.report.ReportDocument;
import com.example.commons.accounts.report.ReportDocument.Tile;
import com.example.commons.accounts.review.ReviewDtos.PopulationEntryResponse;
import com.example.commons.accounts.review.ReviewReportModel.PopulationSection;

/**
 * Lays an account review report out as PDF with OpenPDF, as xlsx with Apache POI's
 * streaming workbook, and as csv.
 */
public class DefaultReviewReportRenderer implements ReviewReportRenderer {

	private static final Color GREEN = new Color(0x15803d);

	private static final Color BLUE = new Color(0x1d4ed8);

	private static final Color RED = new Color(0xb91c1c);

	private static final Color AMBER = new Color(0xb45309);

	private static final Color INK = new Color(0x1f2937);

	private static final List<String> ITEM_HEADERS = List.of("No.", "Name", "Username", "Department", "Roles",
			"Review Outcome", "Remarks", "Review Date");

	private static final List<String> SUSPENDED_HEADERS = List.of("Username", "Name", "Department", "Last Login",
			"Suspended", "Suspended By", "Reason", "Note");

	private static final List<String> REMOVED_HEADERS = List.of("Username", "Name", "Department", "Removed",
			"Removed By", "Reason", "Note");

	@Override
	public byte[] pdf(ReviewReportModel model) {
		DateTimeFormatter dateTime = dateTime(model.zone());
		ReportDocument document = new ReportDocument(title(model) + " Report",
				title(model) + " " + format(model.periodStart(), model.periodEnd()), model.draft());
		document.keyValues(List.of(new String[] { "Review", title(model) },
				new String[] { "Review Period", format(model.periodStart(), model.periodEnd()) },
				new String[] { "Due Date", day(model.dueDate()) },
				new String[] { "Completed",
						model.completedAt() == null ? null
								: dateTime.format(model.completedAt()) + " by " + model.completedBy() },
				new String[] { "Generated On", dateTime.format(model.generatedAt()) },
				new String[] { "Generated By", model.generatedBy() }));
		document.heading("Active Accounts Review Summary");
		List<Tile> tiles = new ArrayList<>(List.of(
				new Tile(String.valueOf(model.summary().confirmed()), "Confirmed (no role changes)", GREEN),
				new Tile(String.valueOf(model.summary().confirmedRolesEdited()), "Confirmed (roles edited)", BLUE),
				new Tile(String.valueOf(model.summary().removed()), "Removed", RED)));
		if (model.summary().pending() > 0) {
			tiles.add(new Tile(String.valueOf(model.summary().pending()), "Pending", AMBER));
		}
		tiles.add(new Tile(String.valueOf(model.summary().total()), "Total accounts", INK));
		document.tiles(tiles);
		document.heading("Breakdown by Department");
		List<String[]> departments = new ArrayList<>();
		for (ReviewReportModel.DepartmentRow row : model.departments()) {
			departments.add(new String[] { row.department(), String.valueOf(row.confirmed()),
					String.valueOf(row.confirmedRolesEdited()), String.valueOf(row.removed()),
					String.valueOf(row.pending()), String.valueOf(row.total()) });
		}
		document.table(List.of("Department", "Confirmed", "Confirmed (Roles Edited)", "Removed", "Pending", "Total"),
				new float[] { 3, 1, 1.4f, 1, 1, 1 }, departments);
		document.heading("Active Accounts: Detailed Results");
		List<String[]> items = new ArrayList<>();
		for (ReviewReportModel.ItemRow row : model.items()) {
			items.add(itemCells(row, dateTime));
		}
		document.table(ITEM_HEADERS, new float[] { 0.6f, 2, 1.6f, 1.6f, 2.4f, 1.8f, 2.6f, 1.8f }, items);
		if (model.privileged()) {
			populationPdf(document, "Suspended Accounts", model.suspended(), SUSPENDED_HEADERS,
					new float[] { 1.6f, 1.8f, 1.4f, 1.6f, 1.6f, 1.2f, 1.4f, 2 }, dateTime, true);
			populationPdf(document, "Removed Accounts", model.removed(), REMOVED_HEADERS,
					new float[] { 1.6f, 1.8f, 1.4f, 1.6f, 1.2f, 1.4f, 2 }, dateTime, false);
		}
		return document.toBytes();
	}

	private static void populationPdf(ReportDocument document, String title, PopulationSection section,
			List<String> headers, float[] widths, DateTimeFormatter dateTime, boolean suspended) {
		document.heading(title);
		document.text(section.confirmed()
				? "Confirmed by " + section.confirmedBy() + " on " + dateTime.format(section.confirmedAt()) + ". "
						+ section.entries().size() + " accounts." + (section.note() == null ? "" : " " + section.note())
				: "Not yet confirmed.");
		document.table(headers, widths, populationCells(section.entries(), dateTime, suspended));
	}

	private static List<String[]> populationCells(List<PopulationEntryResponse> entries, DateTimeFormatter dateTime,
			boolean suspended) {
		List<String[]> rows = new ArrayList<>();
		for (PopulationEntryResponse entry : entries) {
			rows.add(suspended
					? new String[] { entry.username(), entry.name(), entry.department(),
							time(entry.lastLoginAt(), dateTime), time(entry.occurredAt(), dateTime), entry.actor(),
							entry.reasonCode(), entry.reasonNote() }
					: new String[] { entry.username(), entry.name(), entry.department(),
							time(entry.occurredAt(), dateTime), entry.actor(), entry.reasonCode(),
							entry.reasonNote() });
		}
		return rows;
	}

	@Override
	public byte[] xlsx(ReviewReportModel model) {
		DateTimeFormatter dateTime = dateTime(model.zone());
		SXSSFWorkbook workbook = new SXSSFWorkbook(100);
		try {
			CellStyle bold = workbook.createCellStyle();
			Font font = workbook.createFont();
			font.setBold(true);
			bold.setFont(font);
			Sheet summary = workbook.createSheet("Summary");
			int row = 0;
			if (model.draft()) {
				row = writeRow(summary, row, bold, "DRAFT: generated from an open review, not audit evidence");
			}
			row = writeRow(summary, row, null, "Review", title(model));
			row = writeRow(summary, row, null, "Review Period", format(model.periodStart(), model.periodEnd()));
			row = writeRow(summary, row, null, "Due Date", day(model.dueDate()));
			row = writeRow(summary, row, null, "Completed", model.completedAt() == null ? ""
					: dateTime.format(model.completedAt()) + " by " + model.completedBy());
			row = writeRow(summary, row, null, "Generated On", dateTime.format(model.generatedAt()));
			row = writeRow(summary, row, null, "Generated By", model.generatedBy());
			row++;
			row = writeRow(summary, row, bold, "Outcome", "Accounts");
			row = writeRow(summary, row, null, "Confirmed", String.valueOf(model.summary().confirmed()));
			row = writeRow(summary, row, null, "Confirmed (Roles Edited)",
					String.valueOf(model.summary().confirmedRolesEdited()));
			row = writeRow(summary, row, null, "Removed", String.valueOf(model.summary().removed()));
			row = writeRow(summary, row, null, "Pending", String.valueOf(model.summary().pending()));
			row = writeRow(summary, row, null, "Total", String.valueOf(model.summary().total()));
			row++;
			row = writeRow(summary, row, bold, "Department", "Confirmed", "Confirmed (Roles Edited)", "Removed",
					"Pending", "Total");
			for (ReviewReportModel.DepartmentRow department : model.departments()) {
				row = writeRow(summary, row, null, department.department(), String.valueOf(department.confirmed()),
						String.valueOf(department.confirmedRolesEdited()), String.valueOf(department.removed()),
						String.valueOf(department.pending()), String.valueOf(department.total()));
			}
			Sheet active = workbook.createSheet("Active accounts");
			int line = writeRow(active, 0, bold, ITEM_HEADERS.toArray(String[]::new));
			for (ReviewReportModel.ItemRow item : model.items()) {
				line = writeRow(active, line, null, itemCells(item, dateTime));
			}
			if (model.privileged()) {
				populationSheet(workbook, "Suspended accounts", model.suspended(), SUSPENDED_HEADERS, dateTime, true,
						bold);
				populationSheet(workbook, "Removed accounts", model.removed(), REMOVED_HEADERS, dateTime, false, bold);
			}
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			workbook.write(out);
			return out.toByteArray();
		}
		catch (IOException ex) {
			throw new UncheckedIOException(ex);
		}
		finally {
			workbook.dispose();
		}
	}

	private static void populationSheet(SXSSFWorkbook workbook, String name, PopulationSection section,
			List<String> headers, DateTimeFormatter dateTime, boolean suspended, CellStyle bold) {
		Sheet sheet = workbook.createSheet(name);
		int row = writeRow(sheet, 0, null, "Confirmed", section.confirmed() ? "Yes" : "No");
		if (section.confirmed()) {
			row = writeRow(sheet, row, null, "Confirmed By", section.confirmedBy());
			row = writeRow(sheet, row, null, "Confirmed On", dateTime.format(section.confirmedAt()));
			row = writeRow(sheet, row, null, "Note", section.note() == null ? "" : section.note());
		}
		row++;
		row = writeRow(sheet, row, bold, headers.toArray(String[]::new));
		for (String[] cells : populationCells(section.entries(), dateTime, suspended)) {
			row = writeRow(sheet, row, null, cells);
		}
	}

	private static int writeRow(Sheet sheet, int index, CellStyle style, String... values) {
		Row row = sheet.createRow(index);
		for (int column = 0; column < values.length; column++) {
			org.apache.poi.ss.usermodel.Cell cell = row.createCell(column);
			cell.setCellValue(values[column] == null ? "" : values[column]);
			if (style != null) {
				cell.setCellStyle(style);
			}
		}
		return index + 1;
	}

	@Override
	public byte[] csv(ReviewReportModel model) {
		DateTimeFormatter dateTime = dateTime(model.zone());
		StringBuilder csv = new StringBuilder("﻿");
		csv.append(csvLine(ITEM_HEADERS.toArray(String[]::new)));
		for (ReviewReportModel.ItemRow item : model.items()) {
			csv.append(csvLine(itemCells(item, dateTime)));
		}
		return csv.toString().getBytes(StandardCharsets.UTF_8);
	}

	/**
	 * Returns one csv line. A value that a spreadsheet would read as a formula is
	 * prefixed with an apostrophe, so a name cannot run one when the file is opened.
	 */
	private static String csvLine(String... values) {
		List<String> cells = new ArrayList<>();
		for (String value : values) {
			String text = value == null ? "" : value;
			if (!text.isEmpty() && "=+-@\t\r".indexOf(text.charAt(0)) >= 0) {
				text = "'" + text;
			}
			cells.add("\"" + text.replace("\"", "\"\"") + "\"");
		}
		return String.join(",", cells) + "\r\n";
	}

	private static String title(ReviewReportModel model) {
		return model.privileged() ? "Privileged Account Review" : "Non-privileged Account Review";
	}

	private static String[] itemCells(ReviewReportModel.ItemRow row, DateTimeFormatter dateTime) {
		return new String[] { String.valueOf(row.number()), row.name(), row.username(), row.department(), row.roles(),
				row.outcome(), row.remark(), time(row.decidedAt(), dateTime) };
	}

	private static String time(Instant instant, DateTimeFormatter dateTime) {
		return instant == null ? null : dateTime.format(instant);
	}

	private static String format(LocalDate start, LocalDate end) {
		return day(start) + " - " + day(end);
	}

	private static String day(LocalDate date) {
		return DateTimeFormatter.ofPattern("d MMM yyyy", Locale.ENGLISH).format(date);
	}

	private static DateTimeFormatter dateTime(ZoneId zone) {
		return DateTimeFormatter.ofPattern("d MMM yyyy HH:mm", Locale.ENGLISH).withZone(zone);
	}

}
