-- Changeset com/example/commons/session/oidc/jdbc/schema.yaml::oidc-session-schema::commons
CREATE TABLE OIDC_SESSION (SESSION_ID varchar(64) NOT NULL, CREATION_TIME bigint NOT NULL, ISSUER varchar(255) NOT NULL, SUBJECT varchar(255), PROVIDER_SESSION_ID varchar(255), SESSION_INFORMATION varbinary(MAX) NOT NULL, CONSTRAINT OIDC_SESSION_PK PRIMARY KEY (SESSION_ID));

CREATE NONCLUSTERED INDEX OIDC_SESSION_IX1 ON OIDC_SESSION(ISSUER, PROVIDER_SESSION_ID);

CREATE NONCLUSTERED INDEX OIDC_SESSION_IX2 ON OIDC_SESSION(ISSUER, SUBJECT);

CREATE NONCLUSTERED INDEX OIDC_SESSION_IX3 ON OIDC_SESSION(CREATION_TIME);
